name: "Nestor Smart Home Backup"
version: "1.1.0"
slug: "nestor_smart_home_backup"
description: "Sauvegarde et synchronisation vers Azure Storage"
url: "https://github.com/TrecobatGroupe/NestorSmartHomeAddonsDev"
startup: "services"
boot: "auto"
arch:
  - "amd64"
  - "aarch64"
  - "armv7"
image: "acrnestorpoc.azurecr.io/nestor_smart_home_backup"
host_network: true
init: false
hassio_api: true
homeassistant_api: true
hassio_role: "manager"
map:
  - "ssl:rw"
  - "homeassistant_config:rw"
options: {}
schema: {}
