name: "FRP Proxy Client for HassIO"
description: "This tool can be used to setup a FRP proxy to bypass portforwarding"
version: "2.0.0"
slug: "frp_client"
init: false
network: host
startup: services
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
host_network: true
schema:
  serverip: str
  serverport: int
  haport: int
  box_id: str
  domain: str
  tls_cert_file: str
  tls_key_file: str
  tls_ca_file: str
options:
  serverip: ""
  serverport: 7000
  haport: 8123
  box_id: ""
  domain: ""
  tls_cert_file: "/config/certs/client.crt"
  tls_key_file: "/config/certs/client.key"
  tls_ca_file: "/config/certs/ca.crt"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: acrnestorpoc.azurecr.io/frp_client
