name: "FRP Proxy Client for HassIO"
description: "This tool can be used to setup a FRP proxy to bypass portforwarding"
version: "2.0.9"
slug: "frp_client"
init: false
network: host
startup: services
map:
  - ssl:rw
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
host_network: true
schema:
  serverip: str
  serverport: int
  haport: int
  box_id: str
  box_token: str
  domain: str
options:
  serverip: ""
  serverport: 7000
  haport: 8123
  box_id: ""
  domain: "frp.nestor-app.fr"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: acrnestorpoc.azurecr.io/frp_client
